### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vaaski** [vaaski/go-yt-dlp#5]
Planned features include:
- [ ] look into implementing ideas from [bubbletea-app-template](https://github.com/charmbracelet/bubbletea-app-template) 
- [ ] config page containing:
	- [ ] output directory
	- [ ] yt-dlp and ffmpeg paths
	- [ ] custom formats
	- [ ] custom default flags
- [ ] improved `.app` wrapper for MacOS to enable pinning to the dock
	- [ ] look into [CRT frontend](https://github.com/BigJk/crt)
- [ ] look into [ember](https://github.com/maja42/ember) to perhaps embed dependencies and/or config inside of the binary itself
- [ ] dependency management page
- [ ] initial setup page
- [ ] test on linux
- [ ] automated e2e testing
- [ ] dependency downloading for MacOS without brew and linux
- [ ] notarize/sign code:
	- [ ] MacOS
	- [ ] Windows
- [ ] ask nicely to be featured in readme:
	- [ ] [charmbracelet/bubbletea](https://github.com/charmbracelet/bubbletea)
	- [ ] [yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp)
